port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    udp_port: 7882
    use_external_ip: true
    external_ip_only: true
    enable_loopback_candidate: false
redis:
    address: localhost:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
turn:
    enabled: false
    domain: test-turn.yxkjlivekit.online
    tls_port: 5349
    udp_port: 3478
    external_tls: true
keys:
    APIAMPurtnKx5sL: 70E12CM1pjcNzLLTvRsrQieX9aA0pQEJudNRpkHkZSV

logging:
    level: debug
    json: false
